Traceback (most recent call last):
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 51, in single_nb_execution
    executenb(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/home/ryan/.conda/envs/work/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 553, in async_execute
    await self.async_execute_cell(
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/home/ryan/.conda/envs/work/lib/python3.9/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
## # enter your work here - Uncomment the following lines of code and make necessary changes

# def qmax (Cmin, Thi,Tci):
#     qmax = 
#     return qmax 

# qmax = qmax (Cmin, Thi,Tci)

# q =   # Hint :use Eqn 8

# Hint :use Eqn 6 and 7
# Tho = 
# Tco = 

print("Total heat transfer from hot to cold fluid = %1.3f kW" %(q/1000))
#p.check_p02a(q/1000)

print("Gas outlet temprature = %1.3f" %Tho)
print("Water outlet temprature = %1.3f" %Tco)

#p.check_p02b(Tho, Tco)
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-3-36171529d6f0>[0m in [0;36m<module>[0;34m[0m
[1;32m     13[0m [0;31m# Tco =[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     14[0m [0;34m[0m[0m
[0;32m---> 15[0;31m [0mprint[0m[0;34m([0m[0;34m"Total heat transfer from hot to cold fluid = %1.3f kW"[0m [0;34m%[0m[0;34m([0m[0mq[0m[0;34m/[0m[0;36m1000[0m[0;34m)[0m[0;34m)[0m[0;34m[0m[0;34m[0m[0m
[0m[1;32m     16[0m [0;31m#p.check_p02a(q/1000)[0m[0;34m[0m[0;34m[0m[0;34m[0m[0m
[1;32m     17[0m [0;34m[0m[0m

[0;31mNameError[0m: name 'q' is not defined
NameError: name 'q' is not defined

